networks:
  scot-net:
services:
  app:
    build:
      context: ./src_vue
      dockerfile: Dockerfile
    image: scot
    container_name: scot
    volumes:
      - ./src_vue/config:/app/config
      - ./uwsgi.ini:/app/uwsgi.ini
    environment:
      - FLASK_ENV=production
      - UWSGI_INI=/app/uwsgi.ini
#      - FLASK_ENV=development
    ports:
      - "10020:80"
    networks:
      - scot-net

