DROP DATABASE IF EXISTS scot;
CREATE DATABASE scot;

USE scot;

DROP TABLE IF EXISTS time_slices;
CREATE TABLE time_slices (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	start_year SMALLINT UNSIGNED NOT NULL,
	end_year SMALLINT UNSIGNED NOT NULL,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS words;
CREATE TABLE words (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	word VARCHAR(64) NOT NULL UNIQUE,
	PRIMARY KEY (id)
);

DROP TABLE IF EXISTS similar_words;
CREATE TABLE similar_words (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	word1 INT UNSIGNED NOT NULL REFERENCES words(id),
	word2 INT UNSIGNED NOT NULL REFERENCES words(id),
	count INT UNSIGNED NOT NULL,
	time_id INT UNSIGNED NOT NULL REFERENCES time_slices(id),
	PRIMARY KEY (id)
);
