# Server Configuration
flask_host: "127.0.0.1"

# Environment-specific collections
environments:
  dev:
    - de70
    - en_gbooks_42


# Default values to avoid repetition
defaults:
  frontend_info:
    target: "Krise#NN"
    p: 30
    d: 15
  es_info:
    host: "localhost"
    port: 9200
    user: "USER"
    pwd: "PWD"
  db_url: "mysql+pymysql://user:pwd@localhost:3306"
  access: "public"
# Collection configurations
collections:
  de70:
    displayname: "German--Online News-Dependency--1995-2010"
    sentences: "70 Million Sentences"
    db: "DT_de70mlcc_dependency"
    frontend_info: default
    es_info:
      index: "de70"

  en_gbooks_42:
    displayname: "English--Google Books-Syntactic Ngrams--1520-2008--42 Slices"
    db: "DT_google_syntactic_ngrams_42"
    frontend_info:
      target: "bar/NN"
    es_info: null